### ISSUE TITLE
git push error - remote: Permission to bbest/r3-exercises.git denied

### ISSUE THREAD

**Issue by bbest** [noaa-iea/r3-train#62]
from @lavallef originally as https://github.com/noaa-iea/r3-train/issues/34#issuecomment-865303211:

Hi Ben,

I'm trying to push, but I am getting this error. I am able to pull fine. Looks like a permission issue?

![](https://user-images.githubusercontent.com/46360852/122819972-f35c4980-d28f-11eb-8c5c-9d3c6885e957.PNG)

Thanks,
Flo

**Comment by bbest** [comment]
from @7yl4r:

This looks like something you should open a new issue for. You are trying to push to ben's repo instead of your own. This means you didn't fork properly. There are a few ways to fix this but the easiest is probably to start over and be sure you clone your account's fork instead of Ben's.

**Comment by bbest** [comment]
Thanks @7yl4r! Yes, Tylar is correct that you should be writing to your repository, not mine. So the correct repo for you @lavallef is:
 
    https://github.com/lavallef/r3-exercises.git

I see that you correctly created this repo here based on [1.3 Create Github Repository](https://noaa-iea.github.io/r3-train/collaborate.html#13_Create_Github_Repository), and suspect that the trouble began by using my repo (`https://github.com/bbest/r3-exercises.git`) in the next step [1.4 Create RStudio Project](https://noaa-iea.github.io/r3-train/collaborate.html#14_Create_RStudio_Project).

The image shows my repo which you need to substitute with yours:
  
  ![](https://noaa-iea.github.io/r3-train/figs/rstudio_clone-repo.png)

Please try again and let us know if you have any other troubles.

**Comment by ajanefmc** [comment]
This still does not work for me, even switching to the del Windows command with the cmd app.
![image](https://user-images.githubusercontent.com/86071050/122830993-32ea5c00-d2b7-11eb-877b-567d5d9aff11.png)

Here is what that directory looks like.:
![image](https://user-images.githubusercontent.com/86071050/122831043-4bf30d00-d2b7-11eb-8d51-68fe351093aa.png)

Because I cannot push the changes to my R3-exercises repo, I cannot take the next steps and pull the files from the forked R3-training repo to complete lesson 1.

**Comment by 7yl4r** [comment]
@ajanefmc : I think you are on the wrong issue thread. This is the issue about permissions problems. Things have gotten pretty confusing because new issues are being raised in the comments of other issues instead of in their own issue thread. That is okay though; that sort of thing happens a lot when people are new to issue trackers.

Anyway: What you show is progress! We now know the `.git.\index.lock` is not there (which is good). Now as to why git still thinks there is another instance of git running. That remains a mystery. I thought for sure it was the `index.lock` file that git uses to keep track of that.

**Comment by ajanefmc** [comment]
7yl4r: Sorry for posting in the wrong thread, not because I should know better, but because my problem seems related to others posted above, i.e. taking a long time to push/pull to github.  It could be due to a file lock (now seems unlikely) or due to a permission setting with my own repo or a fork?

At this point, I just don't know and it is preventing me from completing lesson 1 and committing a change to the roster.  Lesson 2 looks like I can do most or all of it without pulling from a github fork, but I wouldn't then be able to push it back to my github exercises repo.  Github is new to me (other than fetching info directly from someone else's repo), so do I have the concept right - the push/pull ability is key and being prevented by a lock, permission, or other issue.  It seems that many seem to be having the same problem here.

**Comment by bbest** [comment]
Hi @ajanefmc, please see solution for [`git push` hangs indefinitely · Issue #70 · noaa-iea/r3-train](https://github.com/noaa-iea/r3-train/issues/70).

Essentially you might need to run `git push` in the **Terminal** pane to accept the prompt for authentication method:

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 1
```

Then a web browser should open to allow you to authorize git to push.
